apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-lb.fullname" . }}
  labels:
    {{- include "static-lb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "static-lb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "static-lb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "static-lb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - -zap-devel=false
            {{- range $mapping := .Values.internalIPMappings }}
            - --internal-ip-mapping={{ $mapping }}
            {{- end }}
            {{- range $mapping := .Values.externalIPMappings }}
            - --external-ip-mapping={{ $mapping }}
            {{- end }}
            {{- range $net := .Values.includeIngressIPNets }}
            - --include-ingress-ip-net={{ $net }}
            {{- end }}
            {{- range $net := .Values.includeExternalIPNets }}
            - --include-external-ip-net={{ $net }}
            {{- end }}
            {{- range $net := .Values.excludeIngressIPNets }}
            - --exclude-ingress-ip-net={{ $net }}
            {{- end }}
            {{- range $net := .Values.excludeExternalIPNets }}
            - --exclude-external-ip-net={{ $net }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
