{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "static-lb.labels" . | nindent 4 }}
  name: {{ include "static-lb.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "static-lb.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "static-lb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
